version: '3.8'
services:

  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: innovation-rev-app
    container_name: innovation-rev-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
      - /var/www/public/build
      - ./storage:/var/www/storage
    networks:
      - app-network

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: innovation-rev-web
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: innovation-rev-db
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: innovation_rev
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
